version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - my-network

  app:
    build:
      context: .
    image: user-service-app
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

networks:
  my-network:
    driver: bridge
